name: hellbore
description: A physics-enriched procedural mining game for Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flame_forge2d: ^0.18.0
  flame_audio: ^2.10.0
  flame_riverpod: ^5.0.0
  flutter_riverpod: ^2.5.1
  flame_tiled: ^1.18.0
  hive_flutter: ^1.1.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  fast_noise: ^1.0.3
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
