import 'dart:ui';

import 'package:motherlode/data/ore_types.dart';
import 'package:motherlode/world/sdf_primitives.dart';
import 'package:motherlode/world/stratigraphy.dart';

/// Types of terrain cells in the world grid
enum CellType {
  empty,
  dirt,
  rock,
  sand,
  obsidian,
  lava,
  gas,
  ore,
  bedrock, // Indestructible boundary
}

/// Individual terrain cell with type, SDF value, and optional ore data.
///
/// The terrain uses Signed Distance Fields (SDF) where:
/// - Negative values = inside solid terrain
/// - Positive values = air/empty space
/// - Zero = the exact surface boundary
class TerrainCell {
  CellType type;

  /// Signed distance field value.
  /// Negative = solid interior, positive = air, zero = surface.
  double sdf;

  OreType? oreType; // Non-null only if type == CellType.ore
  bool isDirty; // Needs visual rebuild
  bool hasCreatureSpawn; // Creature should spawn here

  /// Geological stratum this cell belongs to (set during Genesis generation).
  /// Null for cells generated by the legacy WorldGenerator.
  StratumType? stratum;

  TerrainCell({
    this.type = CellType.empty,
    double? sdf,
    double density = 0.0,
    this.oreType,
    this.isDirty = true,
    this.hasCreatureSpawn = false,
    this.stratum,
  }) : sdf = sdf ?? SdfPrimitives.densityToSdf(density);

  /// Backward-compatible density getter.
  /// Maps SDF to the old 0.0-1.0 range (0.0=empty, 1.0=solid).
  double get density => SdfPrimitives.sdfToDensity(sdf);

  /// Backward-compatible density setter.
  /// Converts density to SDF and updates the sdf field.
  set density(double value) {
    sdf = SdfPrimitives.densityToSdf(value);
  }

  /// Whether this cell blocks movement (SDF-based).
  /// A cell is solid when its SDF is negative (inside terrain)
  /// AND its type is not a non-blocking type (lava, gas).
  bool get isSolid =>
      sdf < 0 &&
      type != CellType.empty &&
      type != CellType.lava &&
      type != CellType.gas;

  /// Whether this cell can be drilled
  bool get isDrillable =>
      type == CellType.dirt ||
      type == CellType.rock ||
      type == CellType.sand ||
      type == CellType.obsidian ||
      type == CellType.ore;

  /// Whether this cell is a hazard
  bool get isHazard => type == CellType.lava || type == CellType.gas;

  /// Get the hardness multiplier for drilling resistance
  double get hardness {
    switch (type) {
      case CellType.sand:
        return 0.5;
      case CellType.dirt:
        return 1.0;
      case CellType.rock:
        return 2.0;
      case CellType.obsidian:
        return 4.0;
      case CellType.ore:
        return oreType?.hardness ?? 1.0;
      case CellType.bedrock:
        return double.infinity;
      default:
        return 0.0;
    }
  }

  /// Get the base color for this cell type
  Color get baseColor {
    switch (type) {
      case CellType.sand:
        return const Color(0xFF9E7B4A); // Warm sandy brown
      case CellType.dirt:
        return const Color(0xFF8B6B3D); // Rich brown earth
      case CellType.rock:
        return const Color(0xFF787878); // Medium gray stone
      case CellType.obsidian:
        return const Color(0xFF2D1B3D); // Deep purple-black
      case CellType.lava:
        return const Color(0xFFFF4500); // Bright orange-red
      case CellType.gas:
        return const Color(0xFF00FF4420);
      case CellType.ore:
        return oreType?.color ?? const Color(0xFFFFD700);
      case CellType.bedrock:
        return const Color(0xFF111111);
      case CellType.empty:
        return const Color(0x00000000);
    }
  }

  /// Whether sand/gravel always collapses (no support check needed)
  bool get alwaysCollapses => type == CellType.sand;

  /// Create a copy of this cell
  TerrainCell copy() {
    return TerrainCell(
      type: type,
      sdf: sdf,
      oreType: oreType,
      isDirty: isDirty,
      hasCreatureSpawn: hasCreatureSpawn,
      stratum: stratum,
    );
  }

  /// Convert to serializable map
  Map<String, dynamic> toMap() {
    return {
      'type': type.index,
      'sdf': sdf,
      'oreId': oreType?.name,
      'hasCreature': hasCreatureSpawn,
      if (stratum != null) 'stratum': stratum!.index,
    };
  }

  /// Restore from serialized map
  factory TerrainCell.fromMap(Map<String, dynamic> map) {
    // Support loading both old 'density' format and new 'sdf' format
    final hasSdf = map.containsKey('sdf');
    final stratumIdx = map['stratum'] as int?;
    return TerrainCell(
      type: CellType.values[map['type'] as int],
      sdf: hasSdf ? (map['sdf'] as num).toDouble() : null,
      density: hasSdf ? 0.0 : (map['density'] as num).toDouble(),
      oreType: map['oreId'] != null
          ? OreRegistry.getByName(map['oreId'] as String)
          : null,
      hasCreatureSpawn: map['hasCreature'] as bool? ?? false,
      stratum: stratumIdx != null ? StratumType.values[stratumIdx] : null,
    );
  }
}
